FROM ubuntu:noble
LABEL maintainer=archadept

ENV DEBIAN_FRONTEND noninteractive
ENV TZ Etc/UTC
RUN apt update && apt install -y build-essential \
                                 clang \
                                 clangd \
                                 clang-format \
                                 clang-tidy \
                                 clang-tools \
                                 libc++-dev \
                                 libc++1 \
                                 libc++abi-dev \
                                 libc++abi1 \
                                 libclang-dev \
                                 libclang1 \
                                 liblldb-dev \
                                 libllvm-ocaml-dev \
                                 liblzma-dev \
                                 libncurses6 \
                                 libncursesw6 \
                                 libomp-dev \
                                 libomp5 \
                                 libpython3-all-dev \
                                 lld \
                                 lldb \
                                 llvm \
                                 llvm-dev \
                                 llvm-runtime \
                                 make \
                                 python3-clang \
                                 qemu-system-arm \
                                 unzip \
                                 wget

